# Generated by Django 3.1 on 2020-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200912_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='content',
            field=models.TextField(max_length=512),
        ),
    ]
